name: MacOS Arm Bottling
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - run: brew install -v --build-bottle bastionzero/homebrew-tap/zli-beta

      - run: brew bottle --verbose --json zli-beta --root-url=https://github.com/bastionzero/homebrew-tap/releases/download/zli-beta-6.25.8-beta

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'