name: MacOS Arm Bottling
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - run: brew install --build-bottle bastionzero/tap/zli-beta
      
      - run: brew bottle zli-beta

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'